### ISSUE TITLE
AttributeError: 'av.video.codeccontext.VideoCodecContext' object has no attribute 'close' appeared.

### ISSUE THREAD

**Issue by SoCool668** [camenduru/GVHMR-jupyter#2]
![01](https://github.com/user-attachments/assets/a5635591-d85e-4344-96e4-b173ba6e4b5d)
![02](https://github.com/user-attachments/assets/29079a05-6347-4676-a7c9-ad4dad5161a6)
Hello, thank you for sharing the code. There is a problem that the model could run before, but it could not run two days ago. They are Figure 1 and Figure 2. Is there any way to solve it? I asked AI, and the answer is, 1. Difference in running logic
Previous log:

The program successfully ran the get_video_lwh function and obtained the dimension information (length, width, height) from the video.
There is no AttributeError problem, which means that imageio and pyav process video files normally at this time.
Later log:

AttributeError: 'av.video.codeccontext.VideoCodecContext' object has no attribute 'close' appeared.
The problem comes from imageio trying to release resources (close() method) when calling the pyav plug-in.
This is usually a compatibility problem caused by mismatched pyav or av library versions.

**Comment by camenduru** [comment]
try `pip install imageio==2.31.1`

**Comment by SoCool668** [comment]
![demo01](https://github.com/user-attachments/assets/4327f37e-5285-4ac2-aadd-9c88678c3f44)
Thank you for your answer. After running pip install imageio==2.31.1, the following picture appears. There is no pkl action file in the output file.

**Comment by camenduru** [comment]
add gpu
![image](https://github.com/user-attachments/assets/886c9e09-4f55-495e-806b-d14dadb66a38)

**Comment by SoCool668** [comment]
![Uploading demo02.jpg…]()

**Comment by SoCool668** [comment]
![demo02](https://github.com/user-attachments/assets/ab5d86cb-f716-43f5-8a5b-7fde6e223612)

**Comment by camenduru** [comment]
no

**Comment by SoCool668** [comment]
Thank you, I chose 4T GPU, but there is still no PKL action file exported in OUTPUT

**Comment by camenduru** [comment]
Do not use the copied notebook. Try again without copying the notebook.

**Comment by camenduru** [comment]
![image](https://github.com/user-attachments/assets/7e292345-dadf-4824-93e5-fe82b949a280)

**Comment by camenduru** [comment]
it is working

**Comment by SoCool668** [comment]
Yes, it was running normally like yours a few days ago, and PKL could be exported, but the above problems occurred in the past two days.

**Comment by camenduru** [comment]
Do not use the copied notebook. Try again without copying the notebook.

**Comment by SoCool668** [comment]
OK, thank you very much for your answer.
